### ISSUE TITLE
Factory packages dropped from LTS 7.x

### ISSUE THREAD

**Issue by peti** [opensuse-haskell/configuration#15]
The following LTS-6.x packages are in `openSUSE:Factory` but no longer compile in an LTS-7.x-based environment:

- [x] ~~[ghc-aeson-extra](http://hackage.haskell.org/package/aeson-extra)~~: no longer compiles in LTS-7.x and it doesn't seem like there are patches to fix that
- [x] [ghc-bloomfilter](http://hackage.haskell.org/package/bloomfilter)
- [x] [ghc-data-default-instances-base](http://hackage.haskell.org/package/data-default-instances-base)
- [x] [ghc-esqueleto](http://hackage.haskell.org/package/esqueleto): Build fixed by applying https://github.com/prowdsponsor/esqueleto/pull/149
- [x] [ghc-fdo-notify](http://hackage.haskell.org/package/fdo-notify)
- [x] [ghc-gnuidn](http://hackage.haskell.org/package/gnuidn)
- [x] [ghc-gnutls](http://hackage.haskell.org/package/gnutls)
- [x] [ghc-gsasl](http://hackage.haskell.org/package/gsasl)
- [x] [ghc-network-multicast](http://hackage.haskell.org/package/network-multicast)
- [x] [ghc-network-protocol-xmpp](http://hackage.haskell.org/package/network-protocol-xmpp)
- [x] [ghc-recursion-schemes](http://hackage.haskell.org/package/recursion-schemes)
- [x] [ghc-regex-tdfa-rc](http://hackage.haskell.org/package/regex-tdfa-rc)
- [x] [ghc-torrent](http://hackage.haskell.org/package/torrent)
- [x] [ghc-yesod-default](http://hackage.haskell.org/package/yesod-default)
- [x] [git-annex](http://hackage.haskell.org/package/git-annex)

Now what?

**Comment by mimi1vx** [comment]
aeson-extra ..https://github.com/phadej/aeson-extra/issues/21 - so blocked by recursion-schemes, probadly after this will be back in stackage. But nothing depends on it :)

**Comment by peti** [comment]
Well, if aeson-extra makes it into  LTS 7.x, then we'll automatically have it then.
