### ISSUE TITLE
Investtigate manually edited projects in devel:languages:haskell

### ISSUE THREAD

**Issue by peti** [opensuse-haskell/configuration#5]
The following files exist in devel:languages:haskell, but not in the auto-generated d:l:h:lts:6 repository. We need to investigate what these files do, whether they are important, and whether we need to keep them in the new auto-generated repo, i.e. by creating appropriate patches. Obviously, these files are also accompanied by manual changes in the corresponding spec file that need to be imvestigated and ported, if necessary:

- [x] ghc-OpenGLRaw/_constraints
- [x] ghc-OpenGLRaw/ghc-OpenGLRaw-rpmlintrc
- [x] ghc-X11/ghc-X11.rpmlintrc
- [x] ghc-aeson-compat/remove_nats.patch
- [x] ghc-binary-tagged/remove_nats.patch
- [x] ghc-cereal/ghc-cereal-rpmlintrc
- [x] ghc-deepseq-generics/deepseq-generics.cabal.patch
- [x] ghc-fast-logger/remove-bytestring-builder.patch
- [x] ghc-fgl/ghc-fgl-rpmlintrc
- [x] ghc-gtk3/work-around-pixel-define.patch
- [x] ghc-haskell-src-exts/_constraints
- [x] ghc-http2/cabal-deps.patch
- [x] ghc-language-c/ghc-language-c-rpmlintrc
- [x] ghc-scotty/remove-nats.patch
- [x] ghc-wai/remove-dep.patch
- [x] ghc-warp/cabal-deps.patch
- [x] hdevtools/hdevtools-rpmlintrc
- [x] hscolour/hscolour-rpmlintrc
- [x] pandoc/pandoc-pdf.readme
- [x] xmonad/xmonad.desktop

**Comment by mimi1vx** [comment]
_constraints files sets minimal system req. for OBS builder (mostly RAM , disk ) and are important
￼rpmlintrc files .. mostly unneedend, only supress warnings 

1. remove_nats.patch
2. remove-bytestring-builder.patch 

removes dependency on nats or bytestring-builder which are from ghc-7.10 empty packages and problematic with rpm dependency system ..
 -- same almost all cabal-deps.patch


deepseq-generics.cabal.patch can be dropped , support for cabal file revisions fixes this -- > need mention in changelog about dropping this patch

xmonad.desktop xsessions file used by gdm/kdm/sddm/lightdm to start xmonad ...

￼ ghc-gtk3/work-around-pixel-define.patch -- fix gtk3 build on non x86 archs ..

**Comment by peti** [comment]
All _constraint files are ported to the new tree. Patches were mostly obsolete (except the gtk3 one). rpmlintrc files seem unnecessary with the new versions. I think we got everything.
