### ISSUE TITLE
libnettle 3.x needed in Leap 42.2 to compile

### ISSUE THREAD

**Issue by peti** [opensuse-haskell/configuration#9]
[ghc-nettle](https://build.opensuse.org/package/show/devel:languages:haskell:lts:6/ghc-nettle) does not support the old 2.x version anymore, so an update of libnettle for Leap would be great: https://build.opensuse.org/request/show/408231.

**Comment by trommler** [comment]
Leap 42.2 reached EOL Jan this year. I guess this can be closed. Please reopen if you disagree.
